apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 825200688599.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googleclothes:3a23c392cc7e12db02b4aa0659eaa79dfa81145a
        ports:
        - containerPort: 80
