apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 825200688599.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlemusic:5d1287fb9b2317718d3a348f39449b7ffc4bc621
        ports:
        - containerPort: 80
