apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 825200688599.dkr.ecr.us-west-2.amazonaws.com/shopping-site-phones:48d247c392fd182d9f6112d5b85dad70cd480db4
        ports:
        - containerPort: 80
