apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 825200688599.dkr.ecr.us-west-2.amazonaws.com/shopping-site-phones:796d151c656b893b6b674530940e5980a18ab524
        ports:
        - containerPort: 80
